@extends('layout.admin')

@section('content')
<div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <section class="p-t-20">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="table-data__tool">
                                        <div class="table-data__tool-left" style="margin-top: 25px;">
                                            <div class="rs-select2--light rs-select2--md">
                                                <select name="" id="test" class="myselect">
                                                    <option selected="selected">All Student</option>
                                                    <option value="">Grade 7</option>
                                                    <option value="">Grade 8</option>
                                                    <option value="">Grade 9</option>
                                                    <option value="">Grade 10</option>
                                                    <option value="">Grade 11</option>
                                                    <option value="">Grade 12</option>
                                                </select>
                                            </div>
                                            <div class="rs-select2--light rs-select2--md">
                                                <select name="" id="test" class="myselect" style="color: #808080;">
                                                    <option selected="selected">All Section</option>
                                                    <option value="">section A</option>
                                                    <option value="">section B</option>
                                                    <option value="">section C</option>
                                                    <option value="">section D</option>
                                                    <option value="">section E</option>
                                                    <option value="">section F</option>
                                                    <option value="">section G</option>
                                                    <option value="">section H</option>
                                                    <option value="">section I</option>
                                                </select>
                                            </div>
                                            <button class="au-btn-filter">
                                                <i class="zmdi zmdi-filter-list"></i>filters</button>
                                        </div>
                                        <div class="table-data__tool-right">
                                            <a style="margin-top: 25px;" href="registerstudent.html" class="au-btn au-btn-icon au-btn--green au-btn--small">
                                                    <i class="zmdi zmdi-plus"></i>add student
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                
                                <div class="col-md-12">
                                    
                                    <div class="table-responsive table-responsive-data2">
                                        <table class="table table-data2">
                                            <thead>
                                                <tr>
                                                    <th>LRN</th>
                                                    <th>name</th>
                                                    <th class="text-center">grade level</th>
                                                    <th class="text-center">section</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody id="studentlist">
                                                <!-- student list was generated by using Jquery in student.js -->
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div> 
        </div>

         <!-- modal delete -->
         <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true"
        data-backdrop="delete">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content text-center" style="margin-top: 85%;">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticModalLabel">Delete Student</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>
                            Do you wish to delete this applicant?
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-danger btn-block" data-dismiss="modal" style="margin-top: 0rem;">No</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- end modal delete -->
        
        <!-- modal send -->
        <div class="modal fade" id="sendModal" tabindex="-1" role="dialog" aria-labelledby="sendModalLabel" aria-hidden="true"
        data-backdrop="send">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content text-center" style="margin-top: 85%;">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticModalLabel">Send Message</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <textarea name="" id="" cols="30" rows="5" placeholder="type your message here . . ."></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Send</button>
                        <button type="button" class="btn btn-danger btn-block" data-dismiss="modal" style="margin-top: 0rem;">Cancel</button>
                    </div>
                </div>
            </div>
        </div>