<?php

return [

    'upload_local_temp_path' => 'storage/tmp',
    'upload_path_img_student' => 'app/public/student/',
    'upload_path_img_teacher' => 'app/public/teacher/',
    'upload_path_img_principal' => 'app/public/principal/',


    'gender' => [
        1 => 'Male',
        2 => 'Female'
    ],

    'schedule_time' => [
        1 => '07:30 AM - 08:30 AM',
        2 => '08:30 AM - 09:30 AM',
        3 => '10:00 AM - 11:00 AM',
        4 => '11:00 AM - 12:00 NN',
        5 => '01:00 PM - 2:00 PM',
        6 => '02:00 PM - 03:00 PM',
        7 => '03:00 PM - 04:00 PM',
        8 => '04:00 PM - 05:00 PM',
    ],

    'province' => [
        1 => 'Aklan',
        2 => 'Antique',
        3 => 'Biliran',
        4 => 'Bohol',
        5 => 'Capiz',
        6 => 'Cebu',
        7 => 'EasternSamar',
        8 => 'Guimaras',
        9 => 'Iloilo',
        10 => 'Leyte',
        11 => 'Negros(Occidental)',
        12 => 'Negros(Oriental)',
        13 => 'Northern-Samar',
        14 => 'Samar(Western-Samar)',
        15 => 'Siquijor',
        16 => 'Leyte(Southern)',
        17 => 'Mindanao',
    ],

    'municipality' => [
        'Aklan' => [
            1 => 'Banga',
            2 => 'Ibajay',
            3 => 'Libacao',
            4 => 'Malay',
            5 => 'New Washington',
        ],

        'Antique' => [
            1 => 'Belison',
            2 => 'Culasi',
            3 => 'Libertad',
            4 => 'San Jose',
            5 => 'Sibalom',
            6 => 'Tobias Fornier'
        ],

        'Biliran' => [
            1 => 'Cabucgayan',
            2 => 'Kawayan',
        ],

        'Bohol' => [
            1 => 'Anda',
            2 => 'Balilihan',
            3 => 'Bilar',
            4 => 'Candijay',
            5 => 'Clarin',
            6 => 'Dagohoy',
            7 => 'Dimiao',
            8 => 'Guindulman',
            9 => 'Inabanga',
            10 => 'Lila',
            11 => 'Loon',
            12 => 'Panglao',
            13 => 'Borja',
            14 => 'Sevilla',
            15 => 'Tagbilaran',
            16 => 'Tubigon',

        ],

        'Capiz' => [
            1 => 'Cuartero',
            2 => 'Dao',
            3 => 'Dumalag',
            4 => 'Ivisan',
            5 => 'Jaminda',
            6 => 'Ma-ayon',
            7 => 'Mambusao',
            8 => 'Panitan',
            9 => 'Pilar',
            10 => 'Roxas',
            11 => 'Puntevedra',
            12 => 'Roxas City',
            13 => 'Sapian',
            14 => 'Sigma',
            15 => 'Tapaz',
        ], 

        'Cebu' => [
            1 => 'Alcantara',
            2 => 'Alcoy',
            3 => 'Alegria',
            4 => 'Aloguinsan',
            5 => 'Argao',
            6 => 'Asturias',
            7 => 'Badian',
            8 => 'Balamban',
            9 => 'Bantayan',
            10 => 'Barili',
            11 => 'Bogo',
            12 => 'Boljoon',
            13 => 'Borbon',
            14 => 'Carcar',
            15 => 'Carmen',
            16 => 'Catmon',
            17 => 'Cebu City',
            18 => 'Compostela',
            19 => 'Consolacion',
            20 => 'Cordova',
            21 => 'Daanbantayan',
            22 => 'Dalaguete',
            23 => 'Danao City',
            24 => 'Dumanjug',
            25 => 'Ginatilan',
            26 => 'Lapu-Lapu City',
            27 => 'Liloan',
            28 => 'Mactan',
            29 => 'Madridejos',
            30 => 'Malabuyoc',
            31 => 'Mandaue City',
            32 => 'Medellin',
            33 => 'Mingalanilla',
            34 => 'Moalboal',
            35 => 'Naga',
            36 => 'Oslob',
            37 => 'Pilar',
            38 => 'Pinamungahan',
            39 => 'Poro',
            40 => 'Ronda',
            41 => 'Samboan',
            42 => 'San Fernando',
            43 => 'San Francisco',
            44 => 'San Remegio',
            45 => 'Santa Fe',
            46 => 'Santander',
            47 => 'Sibonga',
            48 => 'Sogod',
            49 => 'Tabogon',
            50 => 'Tabuelan',
            51 => 'Talisay',
            52 => 'Toledo City',
            53 => 'Tuburan',
            54 => 'Tudela',
        ],

        'EasternSamar' => [
            1 => 'Arteche',
            2 => 'Balangiga',
            3 => 'Balangkayan',
            4 => 'Borongan',
            5 => 'Can - avid',
            6 => 'Dolores',
            7 => 'General MacArthur',     
            8 => 'Giporlos',
            9 => 'Guiuan',
            10 => 'Hernani',
            11 => 'Jipapad',
            12 => 'Lawaan',
            13 => 'Llorente',
            14 => 'Maslog',
            15 => 'Maydolong',
            16 => 'Mercedes',
            17 => 'Oras',
            18 => 'Quinapondan',
            19 => 'Salcedo',
            20 => 'San Julian',
            21 => 'San Policarpo',
            22 => 'Sulat',
            23 => 'Taft',               
        ],

        'Guimaras' => [
            1 => 'Buenavista',
            2 => 'Jordan',
            3 => 'Nueva Valencia',
        ],

        'Iloilo' => [
            1 => 'Ajuy',
            2 => 'Alimodian',
            3 => 'Anilao',
            4 => 'Badiangan',
            5 => 'Balasan',
            6 => 'Banate',
            7 => 'Barotac Nuevo',
            8 => 'Batad',
            9 => 'Bingawan',
            10 => 'Cabatuan',
            11 => 'Calinog',
            12 => 'Carles',
            13 => 'Dingle',
            14 => 'Duenas',
            15 => 'Dumangas',
            16 => 'Estancia',
            17 => 'Guimbal',
            18 => 'Igbaras',
            19 => 'IloIlo City',
            20 => 'Janiuay',
            21 => 'Lambunao',
            22 => 'Leganes',
            23 => 'Lemery',
            24 => 'Leon',
            25 => 'Maasin',
            26 => 'Miagao',
            27 => 'Mina',
            28 => 'New Lucena',
            29 => 'Oton',
            30 => 'Paasi',
            31 => 'Pavia',
            32 => 'Pototan',
            33 => 'San Dionisio',
            34 => 'San Enrique',
            35 => 'San Joaquin',
            36 => 'San Miguel',
            37 => 'San Rafael',
            38 => 'Santa Barbara',
            39 => 'Sara',
            40 => 'Tigbuan',
            41 => 'Tubungan',
            42 => 'Zarraga',
        ],

        'Leyte' => [
            1 => 'Tacloban City',
            2 => 'Palo',
            3 => 'Anilao',
            4 => 'Tanuan',
            5 => 'Babatngon',
            6 => 'Burauen',
            7 => 'Carigara',
            8 => 'Abuyog',
            9 => 'Ormoc City',
            10 => 'Baybay City',
            11 => 'Palompon',
            12 => 'Hindang',
            13 => 'Inopacan',
            14 => 'Hilongos',
            15 => 'Matalom',
            16 => 'Estancia',
            17 => 'Maasin City',
            18 => 'Sogod',
            19 => 'Limasawa',
        ],

        'Negros(Occidental)' => [
            1 => 'Bacolod City',
            2 => 'Bago City',
            3 => 'Binalbagan',
            4 => 'Cadiz City',
            5 => 'Calatrava',
            6 => 'Candoni',
            7 => 'Cauayan',
            8 => 'Don Salvador Bendicto',
            9 => 'Enrique Magalona',
            10 => 'Escalante',
            11 => 'Himamaylan',
            12 => 'Hinigaran',
            13 => 'Hinoba -an',
            14 => 'Ilog',
            15 => 'Isabela',
            16 => 'Kabangkalan',
            17 => 'Kauayan',
            18 => 'La Carlota City',
            19 => 'La Catillana',
            20 => 'Manapla',
            21 => 'Moises Padilla',
            22 => 'Murcia',
            23 => 'Paraiso',
            24 => 'Pontevedra',
            25 => 'Pulupandan',
            26 => 'Sagay',
            27 => 'Mina',
            28 => 'San Carlos City',
            29 => 'San Enrique',
            30 => 'Silay City',
            31 => 'Silay Hawaiian Central',
            32 => 'Sipalay',
            33 => 'Talisay',
            34 => 'Valladolid',
            35 => 'Victorias',
        ],

        'Negros(Oriental)' => [
            1 => 'Amlan',
            2 => 'Ayungon',
            3 => 'Bais City',
            4 => 'Basay',
            5 => 'Bayawan',
            6 => 'Bindoy',
            7 => 'Canlaon City',
            8 => 'Dauin',
            9 => 'Dumaguete City',
            10 => 'Guihulngan',
            11 => 'Jimalalud',
            12 => 'La Libertad',
            13 => 'Mabinay',
            14 => 'Pamplona',
            15 => 'San Jose',
            16 => 'Siaton',
            17 => 'Sibulan',
            18 => 'Sta.Catalina',
            19 => 'Tanjay',
            20 => 'Tayasan',
            21 => 'Valencia',
            22 => 'Valle hermoso',
            23 => 'Zamboanguita',
        ],

        'Northern-Samar' => [
            1 => 'Allen',
            2 => 'Biri',
            3 => 'Bobon',
            4 => 'Capul',
            5 => 'Catarman',
            6 => 'Catubig',
            7 => 'Gamay',
            8 => 'La Navas',
            9 => 'Laoang',
            10 => 'Lapineg',
            11 => 'Lavezares',
            12 => 'Lope De Vega',
            13 => 'Mapanas',
            14 => 'Mondragon',
            15 => 'Palapag',
            16 => 'Pambujan',
            17 => 'Rosario',
            18 => 'San Antonia',
            19 => 'San Isidro',
            20 => 'San Roque',
            21 => 'San Vicente',
            22 => 'Silvino Lubos',
            23 => 'Victoria',
        
        ],

        'Samar(Western-Samar)' => [
            1 => 'Almagro',
            2 => 'Basey ',
            3 => 'Calbayog City',
            4 => 'Calbiga',
            5 => 'Catbalogan',
            6 => 'Daram',
            7 => 'Gandara',
            8 => 'Hinbangan',
            9 => 'Jiabong',
            10 => 'Marabut',
            11 => 'Matuguinao',
            12 => 'Motiong',
            13 => 'Pagsangjan',
            14 => 'Pinabacdao',
            15 => 'San Jorge',
            16 => 'San Jose de Bauan',
            17 => 'San Sebastian',
            18 => 'Sta.Margarita',
            19 => 'Sta.Rita',
            20 => 'Sto.Nino',
            21 => 'Tagapulan',
            22 => 'Talarora',
            23 => 'Tarangnan',
            24 => 'Villareal',
            25 => 'Wright',
            26 => 'Zumarraga',
        ],
        
        'Siquijor' => [
            1 => 'Enrique Villanueva',
            2 => 'Larena',
            3 => 'Lazi',
            4 => 'Maria',
            5 => 'San Juan',
            6 => 'Siquijor'
        ],

        'Leyte(Southern)' => [
            1 => 'Anahawan',
            2 => 'Bontoc',
            3 => 'Hinunganan',
            4 => 'Hinundayan',
            5 => 'Libagon',
            6 => 'Liloan',
            7 => 'Limasawa',
            8 => 'Maasin',
            9 => 'Macrohon',
            10 => 'Malitbog',
            11 => 'Padre Burgos',
            12 => 'Pintuyan',
            13 => 'San Francisco',
            14 => 'San Juan',
            15 => 'San Ricardo',
            16 => 'Sogod',
            17 => 'St.Bernard',
            18 => 'Tomas Oppus',
        ],

        'Mindanao' => [
            1 => 'Davao City',
            2 => 'Cagayan De Oro City',
            3 => 'Zamboanga',
            4 => 'Iligan City',
            5 => 'General Santos City',
            6 => 'Butuan City',
            7 => 'Ozamiz City',
            8 => 'Cotabato City',
            9 => 'Marawi City',
            10 => 'Koronadal City',
            11 => 'Dipolog City',
            12 => 'Malaybalay',
            13 => 'Kidapawan City',
            14 => 'Pagadian City',
            15 => 'Digos City',
            16 => 'Basilan',
            17 => 'Tagum',
            18 => 'Mati',
            19 => 'Surigao City',
            20 => 'Valencia City',
            21 => 'Bislig',
            22 => 'Tacurong City',
            23 => 'Oroquieta City',
            24 => 'Laguindingan',
            25 => 'Dapitan City',
            26 => 'Cabadbaran City',
        ]

        


    ]


];
